---
apiVersion: scheduler.config.gardener.cloud/v1alpha1
kind: SchedulerConfiguration
clientConnection:
  acceptContentTypes: application/json
  contentType: application/json
  qps: 100
  burst: 130
leaderElection:
  leaderElect: true
  leaseDuration: 15s
  renewDeadline: 10s
  retryPeriod: 2s
  resourceLock: configmaps
# `discovery` allows specifying options for the cached discovery client.
# discovery:
#   discoveryCacheDir: /tmp/cache-dir
#   httpCacheDir: /tmp/http-cache-dir
#   ttl: 10s
logLevel: info
server:
  http:
    bindAddress: 0.0.0.0
    port: 10251
#schedulers:
#  backupBucket:
#    concurrentSyncs: 5 # defaults to 5
#    retrySyncPeriod: 15s # initial retry period, then uses exponential backoff
#  shoot:
#    concurrentSyncs: 5 # defaults to 5
#    retrySyncPeriod: 15s # initial retry period, then uses exponential backoff
#    candidateDeterminationStrategy: MinimalDistance # either {SameRegion,MinimalDistance}
