#!/bin/bash -e
#
# Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

if [ -z "$1" ]
then
   echo "Setting the path to the landscaper import file is required. The file with path \".landscaper/gardenlet/example/imports.yaml\" can be used as a blueprint. Use \"make start-landscaper-gardenlet IMPORT_PATH=<filepath>\"";
   exit 1
fi

GO111MODULE=on \
OPERATION=RECONCILE \
IMPORTS_PATH=$1 \
COMPONENT_DESCRIPTOR_PATH=.landscaper/gardenlet/example/local/component_descriptor_list.yaml \
    go run \
      -mod=vendor \
      -ldflags "$(./hack/get-build-ld-flags.sh)" \
      "$(dirname $0)"/../../cmd/landscaper-gardenlet/main.go
