// +build !ignore_autogenerated

/*
Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GardenletLandscaperImport) DeepCopyInto(out *GardenletLandscaperImport) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.RuntimeCluster.DeepCopyInto(&out.RuntimeCluster)
	in.GardenCluster.DeepCopyInto(&out.GardenCluster)
	if in.ImageVectorOverwrite != nil {
		in, out := &in.ImageVectorOverwrite, &out.ImageVectorOverwrite
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.ComponentImageVectorOverwrites != nil {
		in, out := &in.ComponentImageVectorOverwrites, &out.ComponentImageVectorOverwrites
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.SeedBackup != nil {
		in, out := &in.SeedBackup, &out.SeedBackup
		*out = new(SeedBackup)
		(*in).DeepCopyInto(*out)
	}
	if in.RevisionHistoryLimit != nil {
		in, out := &in.RevisionHistoryLimit, &out.RevisionHistoryLimit
		*out = new(int32)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	in.ComponentConfiguration.DeepCopyInto(&out.ComponentConfiguration)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GardenletLandscaperImport.
func (in *GardenletLandscaperImport) DeepCopy() *GardenletLandscaperImport {
	if in == nil {
		return nil
	}
	out := new(GardenletLandscaperImport)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GardenletLandscaperImport) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubernetesClusterTargetConfig) DeepCopyInto(out *KubernetesClusterTargetConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubernetesClusterTargetConfig.
func (in *KubernetesClusterTargetConfig) DeepCopy() *KubernetesClusterTargetConfig {
	if in == nil {
		return nil
	}
	out := new(KubernetesClusterTargetConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeedBackup) DeepCopyInto(out *SeedBackup) {
	*out = *in
	if in.Credentials != nil {
		in, out := &in.Credentials, &out.Credentials
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeedBackup.
func (in *SeedBackup) DeepCopy() *SeedBackup {
	if in == nil {
		return nil
	}
	out := new(SeedBackup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Target) DeepCopyInto(out *Target) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Target.
func (in *Target) DeepCopy() *Target {
	if in == nil {
		return nil
	}
	out := new(Target)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetSpec) DeepCopyInto(out *TargetSpec) {
	*out = *in
	out.Configuration = in.Configuration
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetSpec.
func (in *TargetSpec) DeepCopy() *TargetSpec {
	if in == nil {
		return nil
	}
	out := new(TargetSpec)
	in.DeepCopyInto(out)
	return out
}
