// +build !ignore_autogenerated

/*
Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	imports "github.com/gardener/gardener/pkg/landscaper/gardenlet/apis/imports"
	v1 "k8s.io/api/core/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*GardenletLandscaperImport)(nil), (*imports.GardenletLandscaperImport)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_GardenletLandscaperImport_To_imports_GardenletLandscaperImport(a.(*GardenletLandscaperImport), b.(*imports.GardenletLandscaperImport), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*imports.GardenletLandscaperImport)(nil), (*GardenletLandscaperImport)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_imports_GardenletLandscaperImport_To_v1alpha1_GardenletLandscaperImport(a.(*imports.GardenletLandscaperImport), b.(*GardenletLandscaperImport), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*KubernetesClusterTargetConfig)(nil), (*imports.KubernetesClusterTargetConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_KubernetesClusterTargetConfig_To_imports_KubernetesClusterTargetConfig(a.(*KubernetesClusterTargetConfig), b.(*imports.KubernetesClusterTargetConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*imports.KubernetesClusterTargetConfig)(nil), (*KubernetesClusterTargetConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_imports_KubernetesClusterTargetConfig_To_v1alpha1_KubernetesClusterTargetConfig(a.(*imports.KubernetesClusterTargetConfig), b.(*KubernetesClusterTargetConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SeedBackup)(nil), (*imports.SeedBackup)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_SeedBackup_To_imports_SeedBackup(a.(*SeedBackup), b.(*imports.SeedBackup), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*imports.SeedBackup)(nil), (*SeedBackup)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_imports_SeedBackup_To_v1alpha1_SeedBackup(a.(*imports.SeedBackup), b.(*SeedBackup), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Target)(nil), (*imports.Target)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Target_To_imports_Target(a.(*Target), b.(*imports.Target), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*imports.Target)(nil), (*Target)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_imports_Target_To_v1alpha1_Target(a.(*imports.Target), b.(*Target), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TargetSpec)(nil), (*imports.TargetSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_TargetSpec_To_imports_TargetSpec(a.(*TargetSpec), b.(*imports.TargetSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*imports.TargetSpec)(nil), (*TargetSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_imports_TargetSpec_To_v1alpha1_TargetSpec(a.(*imports.TargetSpec), b.(*TargetSpec), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_GardenletLandscaperImport_To_imports_GardenletLandscaperImport(in *GardenletLandscaperImport, out *imports.GardenletLandscaperImport, s conversion.Scope) error {
	if err := Convert_v1alpha1_Target_To_imports_Target(&in.RuntimeCluster, &out.RuntimeCluster, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_Target_To_imports_Target(&in.GardenCluster, &out.GardenCluster, s); err != nil {
		return err
	}
	out.ImageVectorOverwrite = (*runtime.RawExtension)(unsafe.Pointer(in.ImageVectorOverwrite))
	out.ComponentImageVectorOverwrites = (*runtime.RawExtension)(unsafe.Pointer(in.ComponentImageVectorOverwrites))
	out.SeedBackup = (*imports.SeedBackup)(unsafe.Pointer(in.SeedBackup))
	out.RevisionHistoryLimit = (*int32)(unsafe.Pointer(in.RevisionHistoryLimit))
	out.Resources = (*v1.ResourceRequirements)(unsafe.Pointer(in.Resources))
	out.ComponentConfiguration = in.ComponentConfiguration
	return nil
}

// Convert_v1alpha1_GardenletLandscaperImport_To_imports_GardenletLandscaperImport is an autogenerated conversion function.
func Convert_v1alpha1_GardenletLandscaperImport_To_imports_GardenletLandscaperImport(in *GardenletLandscaperImport, out *imports.GardenletLandscaperImport, s conversion.Scope) error {
	return autoConvert_v1alpha1_GardenletLandscaperImport_To_imports_GardenletLandscaperImport(in, out, s)
}

func autoConvert_imports_GardenletLandscaperImport_To_v1alpha1_GardenletLandscaperImport(in *imports.GardenletLandscaperImport, out *GardenletLandscaperImport, s conversion.Scope) error {
	if err := Convert_imports_Target_To_v1alpha1_Target(&in.RuntimeCluster, &out.RuntimeCluster, s); err != nil {
		return err
	}
	if err := Convert_imports_Target_To_v1alpha1_Target(&in.GardenCluster, &out.GardenCluster, s); err != nil {
		return err
	}
	out.ImageVectorOverwrite = (*runtime.RawExtension)(unsafe.Pointer(in.ImageVectorOverwrite))
	out.ComponentImageVectorOverwrites = (*runtime.RawExtension)(unsafe.Pointer(in.ComponentImageVectorOverwrites))
	out.SeedBackup = (*SeedBackup)(unsafe.Pointer(in.SeedBackup))
	out.RevisionHistoryLimit = (*int32)(unsafe.Pointer(in.RevisionHistoryLimit))
	out.Resources = (*v1.ResourceRequirements)(unsafe.Pointer(in.Resources))
	out.ComponentConfiguration = in.ComponentConfiguration
	return nil
}

// Convert_imports_GardenletLandscaperImport_To_v1alpha1_GardenletLandscaperImport is an autogenerated conversion function.
func Convert_imports_GardenletLandscaperImport_To_v1alpha1_GardenletLandscaperImport(in *imports.GardenletLandscaperImport, out *GardenletLandscaperImport, s conversion.Scope) error {
	return autoConvert_imports_GardenletLandscaperImport_To_v1alpha1_GardenletLandscaperImport(in, out, s)
}

func autoConvert_v1alpha1_KubernetesClusterTargetConfig_To_imports_KubernetesClusterTargetConfig(in *KubernetesClusterTargetConfig, out *imports.KubernetesClusterTargetConfig, s conversion.Scope) error {
	out.Kubeconfig = in.Kubeconfig
	return nil
}

// Convert_v1alpha1_KubernetesClusterTargetConfig_To_imports_KubernetesClusterTargetConfig is an autogenerated conversion function.
func Convert_v1alpha1_KubernetesClusterTargetConfig_To_imports_KubernetesClusterTargetConfig(in *KubernetesClusterTargetConfig, out *imports.KubernetesClusterTargetConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_KubernetesClusterTargetConfig_To_imports_KubernetesClusterTargetConfig(in, out, s)
}

func autoConvert_imports_KubernetesClusterTargetConfig_To_v1alpha1_KubernetesClusterTargetConfig(in *imports.KubernetesClusterTargetConfig, out *KubernetesClusterTargetConfig, s conversion.Scope) error {
	out.Kubeconfig = in.Kubeconfig
	return nil
}

// Convert_imports_KubernetesClusterTargetConfig_To_v1alpha1_KubernetesClusterTargetConfig is an autogenerated conversion function.
func Convert_imports_KubernetesClusterTargetConfig_To_v1alpha1_KubernetesClusterTargetConfig(in *imports.KubernetesClusterTargetConfig, out *KubernetesClusterTargetConfig, s conversion.Scope) error {
	return autoConvert_imports_KubernetesClusterTargetConfig_To_v1alpha1_KubernetesClusterTargetConfig(in, out, s)
}

func autoConvert_v1alpha1_SeedBackup_To_imports_SeedBackup(in *SeedBackup, out *imports.SeedBackup, s conversion.Scope) error {
	out.Provider = in.Provider
	out.Credentials = (*runtime.RawExtension)(unsafe.Pointer(in.Credentials))
	return nil
}

// Convert_v1alpha1_SeedBackup_To_imports_SeedBackup is an autogenerated conversion function.
func Convert_v1alpha1_SeedBackup_To_imports_SeedBackup(in *SeedBackup, out *imports.SeedBackup, s conversion.Scope) error {
	return autoConvert_v1alpha1_SeedBackup_To_imports_SeedBackup(in, out, s)
}

func autoConvert_imports_SeedBackup_To_v1alpha1_SeedBackup(in *imports.SeedBackup, out *SeedBackup, s conversion.Scope) error {
	out.Provider = in.Provider
	out.Credentials = (*runtime.RawExtension)(unsafe.Pointer(in.Credentials))
	return nil
}

// Convert_imports_SeedBackup_To_v1alpha1_SeedBackup is an autogenerated conversion function.
func Convert_imports_SeedBackup_To_v1alpha1_SeedBackup(in *imports.SeedBackup, out *SeedBackup, s conversion.Scope) error {
	return autoConvert_imports_SeedBackup_To_v1alpha1_SeedBackup(in, out, s)
}

func autoConvert_v1alpha1_Target_To_imports_Target(in *Target, out *imports.Target, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_TargetSpec_To_imports_TargetSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Target_To_imports_Target is an autogenerated conversion function.
func Convert_v1alpha1_Target_To_imports_Target(in *Target, out *imports.Target, s conversion.Scope) error {
	return autoConvert_v1alpha1_Target_To_imports_Target(in, out, s)
}

func autoConvert_imports_Target_To_v1alpha1_Target(in *imports.Target, out *Target, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_imports_TargetSpec_To_v1alpha1_TargetSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_imports_Target_To_v1alpha1_Target is an autogenerated conversion function.
func Convert_imports_Target_To_v1alpha1_Target(in *imports.Target, out *Target, s conversion.Scope) error {
	return autoConvert_imports_Target_To_v1alpha1_Target(in, out, s)
}

func autoConvert_v1alpha1_TargetSpec_To_imports_TargetSpec(in *TargetSpec, out *imports.TargetSpec, s conversion.Scope) error {
	out.Type = imports.TargetType(in.Type)
	if err := Convert_v1alpha1_KubernetesClusterTargetConfig_To_imports_KubernetesClusterTargetConfig(&in.Configuration, &out.Configuration, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_TargetSpec_To_imports_TargetSpec is an autogenerated conversion function.
func Convert_v1alpha1_TargetSpec_To_imports_TargetSpec(in *TargetSpec, out *imports.TargetSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_TargetSpec_To_imports_TargetSpec(in, out, s)
}

func autoConvert_imports_TargetSpec_To_v1alpha1_TargetSpec(in *imports.TargetSpec, out *TargetSpec, s conversion.Scope) error {
	out.Type = TargetType(in.Type)
	if err := Convert_imports_KubernetesClusterTargetConfig_To_v1alpha1_KubernetesClusterTargetConfig(&in.Configuration, &out.Configuration, s); err != nil {
		return err
	}
	return nil
}

// Convert_imports_TargetSpec_To_v1alpha1_TargetSpec is an autogenerated conversion function.
func Convert_imports_TargetSpec_To_v1alpha1_TargetSpec(in *imports.TargetSpec, out *TargetSpec, s conversion.Scope) error {
	return autoConvert_imports_TargetSpec_To_v1alpha1_TargetSpec(in, out, s)
}
