// +build !ignore_autogenerated

/*
Copyright (c) 2021 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	json "encoding/json"
	unsafe "unsafe"

	imports "github.com/gardener/gardener/pkg/landscaper/gardenlet/apis/imports"
	v1 "k8s.io/api/core/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*Imports)(nil), (*imports.Imports)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Imports_To_imports_Imports(a.(*Imports), b.(*imports.Imports), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*imports.Imports)(nil), (*Imports)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_imports_Imports_To_v1alpha1_Imports(a.(*imports.Imports), b.(*Imports), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SeedBackup)(nil), (*imports.SeedBackup)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_SeedBackup_To_imports_SeedBackup(a.(*SeedBackup), b.(*imports.SeedBackup), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*imports.SeedBackup)(nil), (*SeedBackup)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_imports_SeedBackup_To_v1alpha1_SeedBackup(a.(*imports.SeedBackup), b.(*SeedBackup), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_Imports_To_imports_Imports(in *Imports, out *imports.Imports, s conversion.Scope) error {
	out.RuntimeCluster = in.RuntimeCluster
	out.GardenCluster = in.GardenCluster
	out.ImageVectorOverwrite = (*string)(unsafe.Pointer(in.ImageVectorOverwrite))
	out.ComponentImageVectorOverwrites = (*string)(unsafe.Pointer(in.ComponentImageVectorOverwrites))
	out.SeedBackup = (*imports.SeedBackup)(unsafe.Pointer(in.SeedBackup))
	out.Resources = (*v1.ResourceRequirements)(unsafe.Pointer(in.Resources))
	out.ComponentConfiguration = in.ComponentConfiguration
	return nil
}

// Convert_v1alpha1_Imports_To_imports_Imports is an autogenerated conversion function.
func Convert_v1alpha1_Imports_To_imports_Imports(in *Imports, out *imports.Imports, s conversion.Scope) error {
	return autoConvert_v1alpha1_Imports_To_imports_Imports(in, out, s)
}

func autoConvert_imports_Imports_To_v1alpha1_Imports(in *imports.Imports, out *Imports, s conversion.Scope) error {
	out.RuntimeCluster = in.RuntimeCluster
	out.GardenCluster = in.GardenCluster
	out.ImageVectorOverwrite = (*string)(unsafe.Pointer(in.ImageVectorOverwrite))
	out.ComponentImageVectorOverwrites = (*string)(unsafe.Pointer(in.ComponentImageVectorOverwrites))
	out.SeedBackup = (*SeedBackup)(unsafe.Pointer(in.SeedBackup))
	out.Resources = (*v1.ResourceRequirements)(unsafe.Pointer(in.Resources))
	out.ComponentConfiguration = in.ComponentConfiguration
	return nil
}

// Convert_imports_Imports_To_v1alpha1_Imports is an autogenerated conversion function.
func Convert_imports_Imports_To_v1alpha1_Imports(in *imports.Imports, out *Imports, s conversion.Scope) error {
	return autoConvert_imports_Imports_To_v1alpha1_Imports(in, out, s)
}

func autoConvert_v1alpha1_SeedBackup_To_imports_SeedBackup(in *SeedBackup, out *imports.SeedBackup, s conversion.Scope) error {
	out.Provider = in.Provider
	out.Credentials = *(*json.RawMessage)(unsafe.Pointer(&in.Credentials))
	return nil
}

// Convert_v1alpha1_SeedBackup_To_imports_SeedBackup is an autogenerated conversion function.
func Convert_v1alpha1_SeedBackup_To_imports_SeedBackup(in *SeedBackup, out *imports.SeedBackup, s conversion.Scope) error {
	return autoConvert_v1alpha1_SeedBackup_To_imports_SeedBackup(in, out, s)
}

func autoConvert_imports_SeedBackup_To_v1alpha1_SeedBackup(in *imports.SeedBackup, out *SeedBackup, s conversion.Scope) error {
	out.Provider = in.Provider
	out.Credentials = *(*json.RawMessage)(unsafe.Pointer(&in.Credentials))
	return nil
}

// Convert_imports_SeedBackup_To_v1alpha1_SeedBackup is an autogenerated conversion function.
func Convert_imports_SeedBackup_To_v1alpha1_SeedBackup(in *imports.SeedBackup, out *SeedBackup, s conversion.Scope) error {
	return autoConvert_imports_SeedBackup_To_v1alpha1_SeedBackup(in, out, s)
}
